---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-chart
spec:
  params:
  - name: IMAGE
    description: designated location for the container image
  - name: COMMIT_SHA
    description: git commit sha
  - name: SOURCE_CODE_DIR
    description: path relative to the workingDir where the code was pulled into
    default: source
  - name: CHART_CONTEXT
    description: path relative to SOURCE_CODE_DIR where the chart is located
    default: dist/chart/
  - name: VERSION_SUFFIX
    description: a suffix to be added to the version string
    default: ""
  - name: VALUES_YAML_PATH_REPO
    description: Path in values.yaml where the image repository is to be injected
    default: ".controllerManager.container.image.repository"
  - name: VALUES_YAML_PATH_TAG
    description: Path in values.yaml where the image tag is to be injected
    default: ".controllerManager.container.image.tag"
  - name: TAG_PREFIX
    description: An identifying prefix on which the version tag is to be matched
    default: "helm-"
  - name: caTrustConfigMapName
    type: string
    description: The name of the ConfigMap to read CA bundle data from.
    default: trusted-ca
  - name: caTrustConfigMapKey
    type: string
    description: The name of the key in the ConfigMap that contains the CA bundle data.
    default: ca-bundle.crt
  - name: SBOM_TYPE
    description: >-
      Select the SBOM format to generate. Valid values: spdx, cyclonedx.
      Note: the SBOM from the prefetch task - if there is one - must be in the same format.
    type: string
    default: spdx
  results:
  - description: Digest of the OCI-Artifact just built
    name: IMAGE_DIGEST
  - description: OCI-Artifact repository and tag where the built OCI-Artifact was pushed
    name: IMAGE_URL
  - description: OCI-Artifact reference of the built OCI-Artifact
    name: IMAGE_REF
  - description: Reference of SBOM blob digest to enable digest-based verification from provenance
    name: SBOM_BLOB_URL
    type: string
  steps:
  - name: build-and-push
    image: quay.io/redhat-appstudio/tools@sha256:5fb54dd824fd6b68247fa4bc32fb5a086254fc7b7325eb08da862c5706a3badb
    env:
    - name: IMAGE
      value: "$(params.IMAGE)"
    - name: COMMIT_SHA
      value: "$(params.COMMIT_SHA)"
    - name: SOURCE_CODE_DIR
      value: "$(params.SOURCE_CODE_DIR)"
    - name: CHART_CONTEXT
      value: "$(params.CHART_CONTEXT)"
    - name: VERSION_SUFFIX
      value: "$(params.VERSION_SUFFIX)"
    - name: VALUES_YAML_PATH_REPO
      value: "$(params.VALUES_YAML_PATH_REPO)"
    - name: VALUES_YAML_PATH_TAG
      value: "$(params.VALUES_YAML_PATH_TAG)"
    - name: TAG_PREFIX
      value: "$(params.TAG_PREFIX)"
    securityContext:
      runAsUser: 0
    script: |
      #!/bin/bash
      set -ex
      #TODO: chart name doesn't correspond with component name
      cd "$SOURCE_CODE_DIR"/"$CHART_CONTEXT"

      repository=$(echo "$IMAGE" | cut -d: -f1)
      export repository
      tag=$(echo "$IMAGE" | cut -d: -f2)
      export tag
      yq -i 'eval(strenv(VALUES_YAML_PATH_REPO)) = strenv(repository)' values.yaml
      yq -i 'eval(strenv(VALUES_YAML_PATH_TAG)) = strenv(tag)' values.yaml

      # TODO: see if fetchTags on the clone task can make this redundant
      git fetch --unshallow --tags origin "$COMMIT_SHA"

      # Create a semver compliant chart version:
      # We assume the existence of a git tag of the format "${TAG_PREFIX}X.Y"
      # Suppose that TAG_PREFIX=helm- and the tag is helm-1.2,
      # `git describe --tags` will return helm-1.2-z-W (if the tag is not on the
      # current commit) where z is the number of commits since the appearance of
      # the matching tag and W is an abbreviated SHA.
      # The command below will convert that output to be semver-compatible.
      chart_version=$( \
        git describe --tags --match="${TAG_PREFIX}*" \
        | sed -e "s/^${TAG_PREFIX}//" \
        | sed -e "0,/-/s//\./" \
        | sed -e "0,/-/s//+/" \
      )

      # If the tag is on the current commit, the command will just return the
      # tagged version (e.g. 1.2). In that case, we'll set z to be 0.
      if [[ "$chart_version" =~ ^[^.]*\.[^.]*$ ]]; then
        chart_version=$chart_version.0+$(git rev-parse --short HEAD)
      fi

      # if such tag does not exist, 0.1 will be used and z will be the commits count
      # on the current branch since the dawn of time.
      if [ -z "${chart_version}" ]; then
        chart_version=0.1.$(git rev-list HEAD --count)+$(git rev-parse --short HEAD)
      fi

      chart_version="$chart_version$VERSION_SUFFIX"
      helm package . --version "$chart_version" --app-version "$COMMIT_SHA"

      chart_name=$(helm show chart . | grep -E "^name:" | awk '{print $2}')
      dest="oci://${repository%/*}"
      output=$(helm push "$chart_name"-"$chart_version".tgz "$dest" 2>&1)

      pushed=$(echo "$output" | grep "Pushed" | awk '{print $2}')
      digest=$(echo "$output" | grep "Digest" | awk '{print $2}')
      pushed_url=$(echo "$pushed" | cut -d: -f1)
      pushed_with_digest="${pushed_url}@${digest}"

      echo -n "$pushed" | tee "$(results.IMAGE_URL.path)"
      echo -n "$pushed_with_digest" | tee "$(results.IMAGE_REF.path)"
      echo -n "$digest" | tee "$(results.IMAGE_DIGEST.path)"

      # TODO: set expiration
      tag=${chart_version//+/_}
      expiration=$(date -d "+5 days" +%s)
      # curl -X PUT -H "Authorization: Bearer $TOKEN" \
      # -H "Content-type: application/json" \
      # -d "{'expiration': $expiration}" \
      # https://quay.io/api/v1/repository/redhat-user-workloads-stage/yherzog-tenant/integration-service/tag/$tag
    workingDir: $(workspaces.source.path)
  - name: upload-sbom
    image: quay.io/konflux-ci/appstudio-utils:48c311af02858e2422d6229600e9959e496ddef1@sha256:91ddd999271f65d8ec8487b10f3dd378f81aa894e11b9af4d10639fd52bba7e8
    env:
    - name: IMAGE
      value: "$(params.IMAGE)"
    - name: SBOM_TYPE
      value: "$(params.SBOM_TYPE)"
    script: |
      #!/bin/bash
      ca_bundle=/mnt/trusted-ca/ca-bundle.crt
      if [ -f "$ca_bundle" ]; then
        echo "INFO: Using mounted CA bundle: $ca_bundle"
        cp -vf $ca_bundle /etc/pki/ca-trust/source/anchors
        update-ca-trust
      fi

      cosign attach sbom --sbom sbom.json --type "$SBOM_TYPE" "$(cat "$(results.IMAGE_REF.path)")"

      # Remove tag from IMAGE while allowing registry to contain a port number.
      sbom_repo="${IMAGE%:*}"
      sbom_digest="$(sha256sum sbom.json | cut -d' ' -f1)"
      # The SBOM_BLOB_URL is created by `cosign attach sbom`.
      echo -n "${sbom_repo}@sha256:${sbom_digest}" | tee "$(results.SBOM_BLOB_URL.path)"
    computeResources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
        cpu: 100m
    volumeMounts:
    - name: trusted-ca
      mountPath: /mnt/trusted-ca
      readOnly: true
    workingDir: $(workspaces.source.path)
  volumes:
  - name: trusted-ca
    configMap:
      name: $(params.caTrustConfigMapName)
      items:
        - key: $(params.caTrustConfigMapKey)
          path: ca-bundle.crt
      optional: true
  workspaces:
  - name: source
    description: Workspace containing the source code to build.
